#!/usr/bin/env perl
use Mojo::Base -strict;

use File::Basename 'dirname';
use File::Spec::Functions qw/catdir splitdir/;

# Source directory has precedence
use lib '../core/';

my @base = (splitdir(dirname(__FILE__)), '..');
my $lib = join('/', @base, 'lib');
my $core = join('/', @base, 'core');
-e catdir(@base, 't') ? unshift(@INC, $lib) : push(@INC, $lib);
-e catdir(@base, 't') ? unshift(@INC, $core) : push(@INC, $core);

# Check if Mojolicious is installed;
die <<EOF unless eval 'use Mojolicious::Commands; 1';
It looks like you don't have the Mojolicious framework installed.
Please visit http://mojolicio.us for detailed installation instructions.

EOF

# Start commands for application
Mojolicious::Commands->start_app('MongoTest');
